---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections: 
upload_dir: static/en/uploads
public_path: "/en/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
